language: node_js
node_js:
- '14'
services:
- docker
sudo: required
branches:
  only:
  - master
  - develop
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_d3ce56c58ad6_key -iv $encrypted_d3ce56c58ad6_iv
  -in qcloud.pem.enc -out /tmp/qcloud.pem -d
- chmod 600 /tmp/qcloud.pem
- eval `ssh-agent -s`
- ssh-add /tmp/qcloud.pem
- export TZ='Asia/Shanghai'
install:
- npm install
- npm run build:all
before_script:
- docker login -u changwei1997 -p ${DOCKER_HUB_PASSWORD}
import:
- source: ".travis/master.yml"
  if: branch = master
- source: ".travis/develop.yml"
  if: branch != master
after_success: echo "Build Success!"
after_failure: echo "Build Failure!"
