version: 2.1

commands:
  install-deps:
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get install rsync
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "package-lock.json" }}
            - v1-deps
      - run: |
          npm -v
          npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-deps-{{ checksum "package-lock.json" }}

  build-app:
    steps:
      - run:
          name: build client
          command: npm run build:client
          no_output_timeout: 5m
      - run:
          name: build server
          command: npm run build:server
          no_output_timeout: 5m

  build-docker:
    steps:
      # - run:
      #     name: docker install
      #     command: |          
      #       sudo apt-get remove docker docker-engine docker.io containerd runc
      #       sudo apt-get install apt-transport-https ca-certificates curl gnupg lsb-release
      #       echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
      #       curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
      #       sudo apt-get update && sudo apt-get install docker-ce docker-ce-cli containerd.io
      #     no_output_timeout: 15m
      - run:
          name: docker login
          command: docker login --username changwei1997 --password ${DOCKER_HUB_PASSWORD}
          no_output_timeout: 15m
      - run:
          name: docker build
          command: docker build . -t changwei1997/changwei.me:latest
          no_output_timeout: 15m
      - run:
          name: docker push
          command: docker push changwei1997/changwei.me:latest
          no_output_timeout: 15m

  deploy:
    steps:
      - run:
          name: Deploy to HOST_QCLOUD_SH_1_HOST
          command: |
            ssh-keyscan "${HOST_QCLOUD_SH_1_IP}" >> ~/.ssh/known_hosts 2>/dev/null
            ssh ${HOST_QCLOUD_SH_1_USER}@${HOST_QCLOUD_SH_1_IP} 'sudo mkdir -m 775 -p /root/docker/www.changwei.me'
            rsync -avr --delete ./docker-compose.yml ${HOST_QCLOUD_SH_1_USER}@${HOST_QCLOUD_SH_1_IP}:/root/docker/www.changwei.me/
            ssh ${HOST_QCLOUD_SH_1_USER}@${HOST_QCLOUD_SH_1_IP} 'cd /root/docker/www.changwei.me && docker-compose down --rmi all && docker-compose up -d --force-recreate'

jobs:
  verify:
    docker:
      - image: circleci/node:14.13.0
    steps:
      - install-deps
      - build-app
  deploy:
    docker:
      - image: circleci/node:14.13.0
    steps:
      - install-deps
      - build-app
      - build-docker
      - deploy

workflows:
  workflow:
    jobs:
      - verify:
          filters:
            branches:
              ignore:
                - master
      - deploy:
          filters:
            branches:
              only:
                - master
